INSERT INTO tb_category(name, created_At) VALUES ('SUV', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Hatchback', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Crossover',NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Convertible', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Sedan', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Sport Car',NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Coupe', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Minivan', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Station Wagon',NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Pickup Truck', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('SUV', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Hatchback', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Crossover',NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Convertible', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Sedan', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Sport Car',NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Coupe', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Minivan', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Station Wagon',NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Pickup Truck', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('SUV', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Hatchback', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Crossover',NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Convertible', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Sedan', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Sport Car',NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Coupe', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Minivan', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Station Wagon',NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Pickup Truck', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('SUV', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Hatchback', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Crossover',NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Convertible', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Sedan', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Sport Car',NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Coupe', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Minivan', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Station Wagon',NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Pickup Truck', NOW());

